config/routes.rb
Rails.application.routes.draw do
  get 'locations/start'

  get '/tour/:id', to: 'locations#map', as: 'location'
  get '/tour_stop/:id', to: 'locations#info', as:'tour_stop'

  get 'tour' => 'locations#menu'

  get '/highlights', to: "highlights#show"

  root to: "home#show" 
  # get '/webcam', to: "webcam#show"

  get "/webcam", to: "pages#show"
  get "/kups", to: "pages#show"
  get "/social_media", to: "pages#show"
end

app/models/location.rb
class Location < ActiveRecord::Base
  serialize :pictures, Array
#source:
#http://stackoverflow.com/questions/7394088/rails-get-next-previous-record

  def next
    Location.where("id > ?", self.id).order("id ASC").first || Location.first
  end

  def previous
    Location.where("id < ?", self.id).order("id DESC").first || Location.last
  end
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/highlights_controller.rb
class HighlightsController < ApplicationController
  layout "page"
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "application"
  def show
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  layout "page"
  respond_to :json
  #information on the current location
  def info
    @location = Location.find(params[:id])
  end
  
  #menu view
  def menu
    @locations = Location.all
  end
  
  #shows current location on map
  def map
    @location = Location.find(params[:id])
    @all_locations = Location.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout "page"
  def show
    render ["pages", request.path].join
  end
end

app/controllers/webcam_controller.rb
class WebcamController < ApplicationController
  layout "page"
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/highlights_helper.rb
module HighlightsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/webcam_helper.rb
module WebcamHelper
end

app/views/highlights/show.html.erb
<div id="highlight-carousel" class="carousel slide carousel-fade" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#highlight-carousel" data-slide-to="0" class="active"></li>
    <li data-target="#highlight-carousel" data-slide-to="1"></li>
    <li data-target="#highlight-carousel" data-slide-to="2"></li>
    <li data-target="#highlight-carousel" data-slide-to="3"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="/images/redhot.jpeg">
      <div class="carousel-caption">
        <h3>The Red Hot</h3>
        Distance: 0.6 Miles 
        <br>
        <a href="https://redhottacoma.com" style= "color:white">Website</a>
        <br>
        <br>
      </div>
    </div>
    <div class="item">
      <img src="/images/metronome.jpeg">
      <div class="carousel-caption">
        <h3>Metronome Coffee</h3>
        Distance: 0.7 Miles
        <br>
        <a href="https://metronomecoffee.com" style= "color:white">Website</a>
        <br>
        <br>
      </div>
    </div>

    <div class="item">
      <img src="/images/silkthai.jpeg">
      <div class="carousel-caption">
        <h3>Silk Thai</h3>
        Distance: 0.6 Miles
        <br>
        <a href="https://silkthaicafe.com" style= "color:white">Website</a>
        <br>
        <br>
      </div>
    </div>

    <div class="item">
      <img src="/images/ptd.jpeg">
      <div class="carousel-caption">
        <h3>Point Defiance</h3>
        Distance: 5.2 Miles
        <br>
        <a href="https://pdza.com" style= "color:white">Website</a>
        <br>
        <br>
      </div>
    </div>

  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#highlight-carousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#highlight-carousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>


<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

  <link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css" />
  <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
  <script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
  <title>Puget Sound Experience</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class = "test">


<div id="home-carousel" class="carousel slide carousel-fade" data-ride="carousel">
  <!-- Indicators -->
  
  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    
    <div class="item active">
      <img class="carousel-img" src="/images/carousel/schiff.jpg">
      <div class="carousel-caption">
        <h1 class = "title">The Puget Sound <span style = "font-style: italic;">Experience</span></h1>  
        <br>
        <br>
      </div>
    </div>


    <div class="item">
      <img class="carousel-img" src="/images/carousel/op.jpg">
      <div class="carousel-caption">
        <h1 class = "title">The Puget Sound <span style = "font-style: italic;">Experience</span></h1>
        <br>
        <br>
      </div>
    </div>

    <div class="item">
      <img class="carousel-img" src="/images/carousel/howarth.jpg">
      <div class="carousel-caption">
        <h1 class = "title">The Puget Sound <span style = "font-style: italic;">Experience</span></h1>
        <br>
        <br>
      </div>
    </div>

    <div class="item">
      <img class="carousel-img" src="/images/carousel/thompson.jpg">
      <div class="carousel-caption">
        <h1 class = "title">The Puget Sound <span style = "font-style: italic;">Experience</span></h1>
        <br>
        <br>
      </div>
    </div>

  </div>
  
</div>

<nav class="navbar navbar-default" role="navigation">
  <div class="container" >
      <div>
        <%= link_to "", root_path, :id => 'logo-small' %>
      </div>
    <div class="navbar-header"></div>
  </div>
</nav>



<div class="target">

  <div class="roller-item" style = "background-image: url('http://www.pugetsound.edu/files/pages/_DSC1659.jpg');">
    <div class = "bottom-half">
      <h3>Look around campus</h3>
      <%= link_to "Virtual Tour", tour_path, :class => 'btn btn-default btn-lg', method: :get %> 
    </div>  
  </div>


  <div class="roller-item" style = "background-image: url('http://3.bp.blogspot.com/-g1ix8vRzcJY/UHcCajdqR2I/AAAAAAAAIsk/KuEU9iIc_EI/s1600/Mount+Rainier+Washington+11.jpg');">
    <div class = "bottom-half">
      <h3>Explore Washington's outdoors</h3>
      <%= link_to "Visit Rainier", webcam_path, :class => 'btn btn-default btn-lg', method: :get %>
     </div>
  </div>


  <div class="roller-item" style = "background-image: url('http://www.pugetsound.edu/images/vt/buildings/Wheelock_KUPS.jpg');">
    <div class = "bottom-half">
    <h3>Learn about student-run radio</h3>
        <%= link_to "KUPS Radio", kups_path, :class => 'btn btn-default btn-lg', method: :get %> 
    </div>
  </div>

   <div class="roller-item" style = "background-image: url('http://s3images.coroflot.com/user_files/individual_files/original_274298_4YOI2OmhX8BvcrIs9LziDVRbx.jpg');">
    <div class = "bottom-half">
    <h3>Tacoma Life</h3>
        <%= link_to "Local Highlights", highlights_path, :class => 'btn btn-default btn-lg', method: :get %>
    </div>
  </div>

   <div class="roller-item" style = "background-image: url('http://www2.ups.edu/dcs/dining/OC_2101.jpg');">
    <div class = "bottom-half">
    <h3>Visit us on Facebook and Twitter</h3>
        <%= link_to "Connect", social_media_path, :class => 'btn btn-default btn-lg', method: :get %>
    </div>
  </div>
</div>


</div>
	

  </body> 
</html>

app/views/layouts/page.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    
    <%= javascript_include_tag("https://maps.googleapis.com/maps/api/js?key=AIzaSyCqVNiaRHyWmzfhql0l9qKEUcX7lzWveto") %>
    <%= javascript_include_tag params[:controller], :media => "all" %>
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    
    <title>Puget Sound Experience</title>

   <%= stylesheet_link_tag 'locations', media: 'all', 'data-turbolinks-track' => true %>   
   <%= stylesheet_link_tag 'webcam', media: 'all', 'data-turbolinks-track' => true %>

    </script>
  </head>
  <body>


<div class="top-top">
  <!--
  <%= link_to root_path do %>
      <img id="logo" src="/images/logo.gif" />
      <% end %>
      
  <%= link_to "", root_path, :id => 'logo-small2' %> -->
  <div id="logo-small2"></div>
      <div class="dropdown">
	<button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
	  Menu
	  <span class="caret"></span>
	</button>
	<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
	  <li role="presentation"><a role="menuitem" tabindex="-1" href="<%= root_path %>">Home</a></li>
	  <li role="presentation"><a role="menuitem" tabindex="-1" href="<%= tour_path %>">Tour Home</a></li>
	  <li role="presentation"><a role="menuitem" tabindex="-1" href="<%= webcam_path %>">Mt. Rainier</a></li>
	  <li role="presentation"><a role="menuitem" tabindex="-1" href="<%= kups_path %>">KUPS Radio</a></li>
	  <li role="presentation"><a role="menuitem" tabindex="-1" href="<%= social_media_path %>">Social Media</a></li>
	  <li role="presentation"><a role="menuitem" tabindex="-1" href="<%= highlights_path %>">Tacoma Highlights</a></li>
	  
	</ul>
      </div>
      
      <!--<img id="menu-icon" src="/images/menu_icon.png" /> -->
      
      
    </div>

    <!-- Puget Sound Logo needs to go here -->
    <%= yield %>
    
    <!-- footer needs to go here -->
  </body>
  
</html>

app/views/locations/info.html.erb
<div class="top-bottom">
  <div class="navigation-arrows">

    <div class="left-arrow">
    <%= link_to location_path(@location) do %>
    
    <img src="/images/left_arrow.png" />
    Previous Location
    
    <% end %>
    </div>
   
    <div class="right-arrow"> 
    <%= link_to location_path(@location.next) do %>
   
      Next Location
      <img src="/images/right_arrow.png" />
   
    <% end %>
    </div>
  </div>
</div>
<h1><%= @location.name %></h1>
 
<div>     
  <div id='ninja-slider'>
    <ul>
      <% @location.pictures.each do |picture| %>
      <li><div data-image="<%= picture %>"></div></li>
      <% end %>
      <!--
	  <li><div data-image="http://www.pugetsound.edu/images/vt/buildings/Wheelock_3.jpg"></div></li>
	      <li><div data-image="http://www.pugetsound.edu/images/vt/buildings/_DSC5319.jpg"></div></li>
              <li><div data-image="http://www.pugetsound.edu/images/vt/buildings/WheelockDiversionsTD022.jpg"></div></li>
              <li><div data-image="http://www.pugetsound.edu/images/vt/buildings/wheelockfoodcourt_3057.jpg"></div></li>
              <li><div data-image="http://www.pugetsound.edu/images/vt/buildings/WheelockTD072.jpg"></div></li>
              <li><div data-image="http://www.pugetsound.edu/images/vt/buildings/Wheelock_Celler.jpg" ></div></li> -->
    </ul>
  </div>
</div>

<p><%= @location.long_description %></p>

app/views/locations/map.html.erb
<div class="top-bottom">
 
  <div class="navigation-arrows">

  <div class="left-arrow"> 
  <%= link_to tour_stop_path(@location.previous) do %>
    <img src="/images/left_arrow.png" />
    Previous Location
  <% end %>
   </div>  
  <div class="right-arrow">
  <%= link_to tour_stop_path(@location) do %>
  Next Location
    <img src="/images/right_arrow.png" />

  <% end %>
  </div>
</div>
</div>



<%= content_tag "div", id: "current-location", data: {location:     @location} do %>

<% end %>

<%= content_tag "div", id: "all-locations", data: {locations: @all_locations} do %>

<% end %>

<%= content_tag "div", id: "latitude", data: {latitude: @location.latitude } do %>

<% end %>
<%= content_tag "div", id: "longitude", data: {longitude: @location.longitude } do %>

<% end %>

<div id="map-canvas"></div>

app/views/locations/menu.html.erb
<div class="top-bottom">
  <div class="navigation-arrows">
   <h3>Choose a Location</h3>
  </div>
  
</div>
<div class="menu">
  

  <% @locations.each do |location| %>
  <%= link_to location_path(location) do %>
  <div class="menu-item">
   <div class="location-picture">
     <img class="small-pic" src="<%= location.logo_url %>" />
   </div>
   <div class="location-info">
     <p class="location-name"><%= location.name %></p>
    
     <p class="location-desc"><%= location.short_description %></p>
   </div>
  </div>

  <% end %>
<% end %>

</div>
 

app/views/pages/kups.html.erb
<h1>KUPS Radio</h1> 
<h3>Here's some information about KUPS</h3>
<!-- <script type="text/javascript" src="http://hosted.musesradioplayer.com/mrp.js"></script> -->
<script type="text/javascript">
MRP.insert({
'url':'http://stream.kups.net',
'codec':'mp3',
'volume':100,
'autoplay':false,
'buffering':5,
'title':'KUPS Live Stream',
'wmode':'transparent',
'skin':'simple-gray',
'width':300,
'height':122
});
</script>

<object id="MRPObject" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="300" height="122">
	<param name="movie" value="http://hosted.muses.org/muses-hosted.swf">
	<param name="flashvars" value="url=http://stream.kups.net&amp;lang=auto&amp;codec=mp3&amp;tracking=true&amp;volume=100&amp;autoplay=false&amp;buffering=5&amp;skin=http://hosted.muses.org/muses-simple-gray.xml&amp;title=KUPS Live Stream&amp;welcome=undefined">
	<param name="wmode" value="transparent">
	<param name="allowScriptAccess" value="always">
	<param name="scale" value="noscale">
	<embed name="MRPObject" src="http://hosted.muses.org/muses-hosted.swf" flashvars="url=http://stream.kups.net&amp;lang=auto&amp;codec=mp3&amp;tracking=true&amp;volume=100&amp;autoplay=false&amp;buffering=5&amp;skin=http://hosted.muses.org/muses-simple-gray.xml&amp;title=KUPS Live Stream&amp;welcome=undefined" scale="noscale" wmode="transparent" width="300" height="122" allowscriptaccess="always" type="application/x-shockwave-flash">
</object>

app/views/pages/social_media.html.erb
<!--Twitter-->

<a class="twitter-timeline" href="https://twitter.com/univpugetsound" data-widget-id="536979543567761408">Tweets by @univpugetsound</a>
<script>
  !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
</script>

<!--Facebook-->

<h3> Like us on Facebook! </h3>

<div id="fb-root"></div>
<script>
  (function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
</script>

<div class="fb-like" data-href="https://www.facebook.com/univpugetsound" data-width="500" data-layout="button_count" data-action="like" data-show-faces="false" data-share="true"></div>

<!--Instagram-->

<h3> Follow us on Instagram! </h3>

<!-- SnapWidget -->
<iframe src="http://snapwidget.com/sc/?u=dW5pdnB1Z2V0c291bmR8aW58MTUwfDN8M3x8eWVzfDIwfG5vbmV8b25TdGFydHx5ZXN8bm8=&ve=031214" title="Instagram Widget" class="snapwidget-widget" allowTransparency="true" frameborder="0" scrolling="no" style="border:none; overflow:hidden; width:500px; height:150px"></iframe>

app/views/pages/webcam.html.erb
<h1>Go visit Rainier National Park</h1> 
<p>Here's the webcam - I'll put some more description in here after we meet with Chris on Wednesday. </p>
<img src="http://www.nps.gov/webcams-mora/mountain.jpg?2014926123654" alt="Mountain View" class="webcam-img">

app/views/webcam/show.html.erb
<h1>Go visit Rainier National Park</h1> 
<p>Here's the webcam - I'll put some more description in here after we meet with Chris on Wednesday. </p>
<img src="http://www.nps.gov/webcams-mora/mountain.jpg?2014926123654" alt="Mountain View" class="webcam-img">